# To Do:WIll improve this later 
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: empirico_cdss_frontend
    ports:
      # Nginx on the droplet proxies to localhost:3000
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - api

