"""
Conversation generation for Empirico.

The app does not run model inference, vector search, or web crawling locally.
All medical evidence retrieval and answer generation is delegated to the shared
Empirico Model Service.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
from datetime import datetime, timedelta
from typing import AsyncGenerator, Optional

from healthnavi.core.constants import CACHE_TTL_MINUTES, MAX_CACHE_SIZE
from healthnavi.services.evidence_retrieval_adapter import generate_model_service_response

logger = logging.getLogger(__name__)

STREAM_CHUNK_SIZE = 220
USER_SAFE_GENERATION_ERROR = "I couldn't complete this answer right now. Please try again."
RESPONSE_CACHE: dict[str, tuple[tuple[str, bool, str, list[str]], datetime]] = {}


def user_friendly_genai_error(_exception: BaseException) -> str:
    """Map model-service failures to a short, safe message for the UI."""
    return USER_SAFE_GENERATION_ERROR


def is_diagnosis_complete(_response: str) -> bool:
    """
    Compatibility flag for the existing API schema.

    Empirico now returns evidence answers rather than staged diagnosis workflows,
    so responses are considered complete once the model service returns them.
    """
    return True


def generate_followup_questions_sync(_original_query: str, _response: str) -> list[str]:
    """
    Backward-compatible no-op.

    Follow-up questions are generated by the shared model service adapter, not
    by an in-app model client.
    """
    return []


async def generate_response(
    query: str,
    chat_history: str,
    patient_data: str,
    deep_search: bool = False,
    user_role_from_db: Optional[str] = None,
) -> tuple[str, bool, str, list[str]]:
    """Generate an evidence-backed answer through the shared model service."""
    cache_key = None
    if not chat_history or chat_history == "No previous conversation":
        cache_key = _generate_cache_key(query, patient_data, deep_search)
        cached_response = _get_cached_response(cache_key)
        if cached_response:
            return cached_response

    try:
        response, diagnosis_complete, prompt_type, followup_questions = (
            await generate_model_service_response(
                query=query,
                chat_history=chat_history,
                patient_data=patient_data,
                deep_search=deep_search,
                user_role_from_db=user_role_from_db,
            )
        )
    except Exception as exc:
        logger.error("Model service generation failed: %s", exc, exc_info=True)
        return user_friendly_genai_error(exc), False, "model_service_error", []

    result = (
        response,
        bool(diagnosis_complete),
        prompt_type,
        followup_questions or [],
    )
    if cache_key:
        _cache_response(cache_key, result)
    return result


async def generate_response_stream(
    query: str,
    chat_history: str,
    patient_data: str,
    deep_search: bool = False,
    user_role_from_db: Optional[str] = None,
) -> AsyncGenerator[str, None]:
    """
    Stream a model-service answer to the existing frontend.

    The model-service response is currently received as one HTTP response, then
    chunked here so the UI keeps its streaming behavior without local inference.
    """
    response, _diagnosis_complete, _prompt_type, followup_questions = await generate_response(
        query=query,
        chat_history=chat_history,
        patient_data=patient_data,
        deep_search=deep_search,
        user_role_from_db=user_role_from_db,
    )

    for chunk in _chunk_text(response):
        yield chunk
        await asyncio.sleep(0)

    if followup_questions:
        followup_json = json.dumps(followup_questions)
        yield f"\n\n[FOLLOWUP_QUESTIONS]:{followup_json}"


def _chunk_text(text: str, chunk_size: int = STREAM_CHUNK_SIZE) -> list[str]:
    if not text:
        return []

    chunks: list[str] = []
    remaining = text
    while len(remaining) > chunk_size:
        split_at = remaining.rfind(" ", 0, chunk_size)
        if split_at >= chunk_size // 2:
            chunks.append(remaining[: split_at + 1])
            remaining = remaining[split_at + 1 :]
        else:
            split_at = chunk_size
            chunks.append(remaining[:split_at])
            remaining = remaining[split_at:]

    if remaining:
        chunks.append(remaining)
    return chunks


def _generate_cache_key(query: str, patient_data: str, deep_search: bool = False) -> str:
    mode = "deep" if deep_search else "quick"
    combined = f"{query}|{patient_data}|{mode}".lower().strip()
    return hashlib.md5(combined.encode()).hexdigest()


def _get_cached_response(cache_key: str) -> tuple[str, bool, str, list[str]] | None:
    cached = RESPONSE_CACHE.get(cache_key)
    if cached is None:
        return None
    response, timestamp = cached
    if datetime.now() - timestamp < timedelta(minutes=CACHE_TTL_MINUTES):
        return response
    RESPONSE_CACHE.pop(cache_key, None)
    return None


def _cache_response(cache_key: str, response: tuple[str, bool, str, list[str]]) -> None:
    RESPONSE_CACHE[cache_key] = (response, datetime.now())
    if len(RESPONSE_CACHE) <= MAX_CACHE_SIZE:
        return
    for key, _value in sorted(RESPONSE_CACHE.items(), key=lambda item: item[1][1])[:20]:
        RESPONSE_CACHE.pop(key, None)
